# Generated by Django 5.0.7 on 2024-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
