# Generated by Django 5.0.7 on 2024-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
